AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Code to implement available flight rules given two dates and two desired airports
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 200
    Runtime: go1.x
    Environment:
      Variables:
        RYANAIR_ROUTES_API: 'https://services-api.ryanair.com/views/locate/3/routes'
        RYANAIR_SCHEDULES_API: 'https://services-api.ryanair.com/timtbl/3/schedules/%s/%s/years/%d/months/%d'
        MAX_INTERCONNECT_WAIT: '2h'
        TIME_LAYOUT: '2006-01-02T15:04'

Parameters:
  stage:
    Type: String
    Default: develop

Resources:
  RyanairFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      FunctionName: !Sub ryanair-flight-connections-${stage}
      CodeUri: s3://ryanair-golang-lambda-test-otavio/ryanairflights.zip
      Handler: ryanairflights
      MemorySize: 128

  RyanairLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${RyanairFunction}
      RetentionInDays: 30
    DependsOn: RyanairFunction